// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nubi.Core.Infrastructure.Data.Context;

namespace Nubi.Core.Infrastructure.Data.Migrations
{
    [DbContext(typeof(UsuarioDbContext))]
    [Migration("20211117194654_initialLocal")]
    partial class initialLocal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nubi.Core.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "LastName1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.1@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName1",
                            Password = "da2cb7f780b225403e5487ce7d40feaa0283f663ce05c7882df100110e8aae86"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "LastName2",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.2@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName2",
                            Password = "e95a7a5547e515340590caa15cbaa99914f594f1398e24e9cfd5207fb66dc0ff"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "LastName3",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.3@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName3",
                            Password = "c02e7b0531c16cf9f95c1686fb9497c052aebe4ca9a3bf00fbc83c11245df53c"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "LastName4",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.4@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName4",
                            Password = "3e3c9fc79e9983f129e8c2868087a366de92423d0fc9cfe39b4b43b9715b0fe6"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "LastName5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.5@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName5",
                            Password = "94137b5c6376f43518d5d158803e477fb33add3da1b4cf49bfa7ce57f09d4ad2"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "LastName6",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.6@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName6",
                            Password = "7c7bc4898dcac630e60c547a30157d0b4ebf38a43b0ccb830d1660025cbc501f"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "LastName7",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.7@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName7",
                            Password = "83f164ce80cfaa93ece1883784d17c4d88451f76b07456cdc8af3020847fb56b"
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "LastName8",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.8@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName8",
                            Password = "ce62fe20d866e1e69de326a4f01b7a92b1ee4f1a3df9ae6698196178900b1723"
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "LastName9",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.9@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName9",
                            Password = "343fb0969817815b1eb788c549b2a27601366b57ba383dc8ba46e39e64e5e6bf"
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "LastName10",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.10@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName10",
                            Password = "7562a64cdd0a4a1f7d9e77a50dcdc52ffe6a59db7d196293caa5e25a15a9e367"
                        },
                        new
                        {
                            Id = 11,
                            Apellido = "LastName11",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.11@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName11",
                            Password = "e4d79a53b370e1c11e4b10905fa6325c524a1e9beb6a4612dbf72460da0325b2"
                        },
                        new
                        {
                            Id = 12,
                            Apellido = "LastName12",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.12@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName12",
                            Password = "0d01e6313118ce3b9367556387930a3ebfdce61a629befacdf7afdad43245a8d"
                        },
                        new
                        {
                            Id = 13,
                            Apellido = "LastName13",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.13@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName13",
                            Password = "5a2713bbbaf02b5ccd0ddefea7585bd00ac6433bb75d5ac8e33d4af9b0505b6e"
                        },
                        new
                        {
                            Id = 14,
                            Apellido = "LastName14",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.14@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName14",
                            Password = "433469d27acfdac401ca6dccfa117f862f88ab196db90351a2d3a455f6425562"
                        },
                        new
                        {
                            Id = 15,
                            Apellido = "LastName15",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.15@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName15",
                            Password = "fefdbc0ad406198526298fa68616ab7590845ebb4b6610cd95b7d94fcb4a9327"
                        },
                        new
                        {
                            Id = 16,
                            Apellido = "LastName16",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.16@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName16",
                            Password = "bb207afb4c102f15ae931f4b61c4ab41f91fec28a7eeca31f9be6032a9241a5e"
                        },
                        new
                        {
                            Id = 17,
                            Apellido = "LastName17",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.17@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName17",
                            Password = "c83de05a9ad9c1166c2b7a44ad2c306fced3a2bed18474432086f864abd04571"
                        },
                        new
                        {
                            Id = 18,
                            Apellido = "LastName18",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.18@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName18",
                            Password = "7d46c9a102dd94082b0df0f06aa9b69256bec64f0c915ed34245235beaa673a1"
                        },
                        new
                        {
                            Id = 19,
                            Apellido = "LastName19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.19@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName19",
                            Password = "462baa5d5c9865c59270375ad5bf4c5856372ddec84deefd9af2f15a03756142"
                        },
                        new
                        {
                            Id = 20,
                            Apellido = "LastName20",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email.20@example.com",
                            IsDeleted = false,
                            Nombre = "FirstName20",
                            Password = "69ef1883caee50de909a3f11fda6937a483da453fd363467642982830570d2b8"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
